package echosentrymiddleware

import (
	"strings"
	"unicode/utf8"

	"github.com/getsentry/sentry-go"
	"github.com/labstack/echo/v5"
)

const (
	// MaxTagNameLength is the maximum length of a Sentry tag name.
	MaxTagNameLength = 200
	// MaxTagValueLength is the maximum length of a Sentry tag value.
	MaxTagValueLength = 200
)

var tagValueReplacer = strings.NewReplacer("\n", " ", "\r", " ", "\t", " ")

func limitString(str string, size int) string {
	if size <= 0 || len(str) <= size {
		return str
	}

	// Walk back at most utf8.UTFMax-1 bytes to the start of the last rune.
	end := size
	for end > 0 && !utf8.RuneStart(str[end]) {
		end--
	}

	// Confirm the trimmed prefix decodes cleanly; if the boundary rune is
	// itself malformed, drop it.
	if r, _ := utf8.DecodeLastRuneInString(str[:end]); r == utf8.RuneError {
		for end > 0 && !utf8.RuneStart(str[end-1]) {
			end--
		}

		if end > 0 {
			end--
		}
	}

	return str[:end]
}

func limitStringWithDots(str string, size int) string {
	const minDotsLimit = 10

	if size <= 0 {
		return str
	}

	if size <= minDotsLimit {
		return limitString(str, size)
	}

	result := limitString(str, size-3)

	if result == str {
		return str
	}

	return result + "..."
}

func prepareTagValue(str string) string {
	str = tagValueReplacer.Replace(str) // no line breaks in tags

	return limitStringWithDots(str, MaxTagValueLength)
}

func prepareTagName(str string) string {
	return limitString(str, MaxTagNameLength)
}

func setTag(span *sentry.Span, tag, value string) {
	if tag == "" {
		return
	}

	span.SetTag(prepareTagName(tag), prepareTagValue(value))
}

func getRequestID(ctx *echo.Context) string {
	requestID := ctx.Request().Header.Get(echo.HeaderXRequestID) // request-id generated by reverse-proxy
	if requestID == "" {
		// missed request-id from proxy, got generated one by middleware.RequestID()
		requestID = ctx.Response().Header().Get(echo.HeaderXRequestID)
	}

	return requestID
}
