package echo_sentry_middleware

import (
	"crypto/rand"
	"fmt"
	"strings"

	"github.com/getsentry/sentry-go"
	"github.com/labstack/echo/v4"
)

func prepareTagValue(str string) string {
	size := 200                               // limit of sentry
	str = strings.Replace(str, "\n", " ", -1) // no \n ib strings
	if len(str) > size {
		return str[:size-3] + "..."
	}

	return str
}

func prepareTagName(str string) string {
	size := 32 // limit of sentry
	if len(str) > size {
		return str[:size]
	}

	return str
}

func setTag(span *sentry.Span, tag, value string) {
	if tag == "" || value == "" {
		return
	}

	span.SetTag(prepareTagName(tag), prepareTagValue(value))
}

func getRequestID(ctx echo.Context) string {
	requestID := ctx.Request().Header.Get(echo.HeaderXRequestID) // request-id generated by reverse-proxy
	if requestID == "" {
		requestID = generateToken() // missed request-id from proxy, we generate it manually
	}
	return requestID
}

func generateToken() string {
	b := make([]byte, 16)
	_, _ = rand.Read(b)
	return fmt.Sprintf("%x", b)
}
